call pathogen#infect()
syntax on

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"
" TABS
"
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set tabstop=4
set shiftwidth=4
set softtabstop=4
set smarttab
set expandtab
set nobackup
set nowritebackup

filetype on
filetype plugin indent on

autocmd Filetype xml setlocal autoindent nocindent nosmartindent indentexpr=
autocmd Filetype html setlocal autoindent nocindent nosmartindent indentexpr=


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"
" HISTORY
"
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set viminfo='1000,f1,\"500

augroup resCur
    autocmd!
    autocmd BufReadPost * call setpos(".", getpos("'\""))
augroup END

set undofile
set undodir=$HOME/.vim/undo
set undolevels=1000
set undoreload=10000


"runtime! config/tabs.vim
"runtime! config/history.vim
runtime! config/functions.vim
runtime! config/lineno.vim
" runtime! config/keybinds.vim

augroup MikeAutocommands
    autocmd!
    autocmd VimResized * execute "normal! \<c-w>="
augroup end

hi StatusLine cterm=reverse ctermfg=3 ctermbg=7 gui=none
hi StatusLineNC cterm=reverse ctermfg=0 ctermbg=7 gui=none

set wildmode=list:longest

let mapleader = ","
nnoremap <leader>r :source $MYVIMRC<cr>:echo "Reloaded .vimrc"<cr>
nnoremap <leader>f :echo expand('%:p')<cr>
nnoremap <leader>s :call RStrip()<cr>:echo "Stripped trailing whitespace."<cr>
noremap <leader>l :set number!<cr>

nnoremap <C-j> 10jz.
nnoremap <C-k> 10kz.
nnoremap <C-f> <C-w>_

nnoremap <C-c> <nop>
inoremap <C-c> <esc>l
nnoremap q: <nop>

" Sets special characters to display for trailing space
" and other obnoxious characters.
" 	    <- for a tab
" ░     <- for trailing whitespace
" ␣     <- non-blocking space
set listchars=tab:⇥\ ,trail:░,nbsp:␣
set list
