call pathogen#infect()
runtime! config/plug.vim

runtime! config/basics.vim
runtime! config/functions.vim
runtime! config/filetypes.vim
runtime! config/fzf.vim
"runtime! config/restore.vim
runtime! config/history.vim
runtime! config/lineno.vim
runtime! config/keybinds.vim
runtime! config/statusline.vim
runtime! config/vim-highlightedyank.vim
runtime! config/startify.vim
runtime! config/ale.vim
runtime! config/languageclient.vim
runtime! config/ncm.vim
