call pathogen#infect()
syntax on

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"
" TABS
"
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set tabstop=4
set shiftwidth=4
set softtabstop=4
set smarttab
set expandtab
set nobackup
set nowritebackup

filetype on
filetype plugin indent on

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"
" HISTORY
"
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set viminfo='1000,f1,\"500

set undofile
set undodir=$HOME/.vim/undo
set undolevels=1000
set undoreload=10000

augroup FileTypes
    autocmd!
    autocmd Filetype xml setlocal autoindent nocindent nosmartindent indentexpr=
    autocmd Filetype html setlocal autoindent nocindent nosmartindent indentexpr=
    autocmd Filetype vim nnoremap <leader>R :source $MYVIMRC<cr>:echo "Reloaded .vimrc"<cr>
augroup end

augroup RestoreCursor
    autocmd!
    autocmd BufReadPost * call setpos(".", getpos("'\""))
augroup end

augroup EqualizeWindowsOnResize
    autocmd!
    autocmd VimResized * execute "normal! \<c-w>="
augroup end

"runtime! config/tabs.vim
"runtime! config/history.vim
runtime! config/functions.vim
runtime! config/lineno.vim
" runtime! config/keybinds.vim

hi StatusLine cterm=reverse ctermfg=3 ctermbg=7 gui=none
hi StatusLineNC cterm=reverse ctermfg=0 ctermbg=7 gui=none

set statusline=%F

set wildmode=list:longest

let mapleader = ","
noremap <leader>l :set number!<cr>
nnoremap <F4> :call RStrip()<cr>:echo "Stripped trailing whitespace."<cr>
nnoremap <leader>j :new<cr>:setlocal buftype=nofile bufhidden=wipe nobuflisted noswapfile<cr>!!jira show<cr>

" Requires NERDTree
nnoremap <leader>t :NERDTreeToggle<cr>
let g:NERDTreeShowHidden = 1

" Requires fzf.vim
nnoremap <leader>r :Rg<cr>
nnoremap <leader>f :History<cr>
nnoremap <leader>o :Files<cr>
nnoremap <leader>gc :Commits<cr>
nnoremap <leader>gf :BCommits<cr>

" Requires vim-fugitive
nnoremap <leader>gb :Gblame<cr>

noremap <C-j> <C-d>z.
noremap <C-k> <C-u>z.

set scroll=10

nnoremap <C-f> <C-w>_
nnoremap <C-w>+ :resize +5<cr>
nnoremap <C-w>- :resize -5<cr>

inoremap <C-c> <esc>
inoremap <C-n> <nop>
inoremap <C-p> <nop>

" For vim-gitgutter
set updatetime=100

" Sets special characters to display for trailing space
" and other obnoxious characters.
"
" See: https://www.compart.com/en/unicode/
" May require ttf-ancient-fonts package:
"
"     $ sudo apt-get install ttf-ancient-fonts
"
" 🞘🞝🞝🞝   <- for a tab
" ░░░    <- for trailing whitespace
" ␣      <- non-breaking space
set listchars=tab:🞘🞝,trail:░,nbsp:␣
set list
